repos:
  - repo: local
    hooks:
      - id: ruff
        name: Ruff
        entry: ruff check
        language: system
        types: [python]
        args: [--fix]
      - id: ruff-format
        name: Ruff
        entry: ruff check
        language: system
        types: [python]
        args: [--fix]
