version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_service
    networks:
      - app_network
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    configs:
      - source: redis_config
        target: /usr/local/etc/redis/redis.conf

  neo4j:
    image: neo4j:latest
    container_name: neo4j_service
    networks:
      - app_network
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/test  # Username: neo4j, Password: test
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    configs:
      - source: neo4j_config
        target: /var/lib/neo4j/conf/neo4j.conf

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_service
    networks:
      - app_network
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_service
    networks:
      - app_network
    depends_on:
      - redis
      - neo4j
      - ollama
    environment:
    - REDIS_PORT=6379
    - NEO4J_URI=bolt://neo4j_service:7687
    - NEO4J_USER=neo4j
    - NEO4J_PASSWORD=password
    - OLLAMA_HOST=http://ollama_service:11434
    - BOOK_PATH=/app/books
    volumes:
      - .:/app
    command: ["python", "src/main.py"]

networks:
  app_network:
    driver: bridge

volumes:
  redis_data:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  ollama_data:

configs:
  redis_config:
    file: ./config/redis.conf
  neo4j_config:
    file: ./config/neo4j.conf