services:
  neuro-trail:
    build: . # Build from the Dockerfile in the current directory
    network_mode: "host"
    ports:
      - "8503:8503"
    env_file: .env
    volumes:
      - ./.env:/app/.env
      - ./src:/app/src
      - ./.data:/app/src/.data

networks:
  host:
    name: host
    external: true
