services:
  redis:
    image: redis:latest
    container_name: redis_service
    networks:
      - app_network
    ports:
      - "6380:6379"  # Maps Redis inside Docker to localhost:6380
    volumes:
      - redis_data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf  # Ensure config is mounted
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  neo4j:
    image: neo4j:latest
    container_name: neo4j_service
    networks:
      - app_network
    ports:
      - "7475:7474"  # Host port 7475 for HTTP
      - "7688:7687"  # Host port 7688 for Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_CONF=/conf  # Tell Neo4j to load config from /conf
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
      - ./config/neo4j.conf:/conf/neo4j.conf  # Mount the local neo4j.conf into /conf (writable)

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_service
    networks:
      - app_network
    ports:
      - "11435:11434"  # Host port 11435 to avoid conflicts
    volumes:
      - ollama_data:/root/.ollama
      - ./scripts/ollama_entrypoint.sh:/usr/local/bin/ollama_entrypoint.sh
    entrypoint: ["/bin/bash", "/usr/local/bin/ollama_entrypoint.sh"]

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: neuro-trail
    networks:
      - app_network
    depends_on:
      - redis
      - neo4j
      - ollama
    environment:
      - REDIS_HOST=redis_service
      - REDIS_PORT=6379
      - NEO4J_URI=bolt://neo4j_service:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - OLLAMA_HOST=http://ollama:11434  # Use service name instead of localhost
      - BOOK_PATH=/app/books
      - OLLAMA_MODEL=deepseek-r1:1.5b
    volumes:
      - .:/app
    command: ["uv", "run", "main.py"]

networks:
  app_network:
    driver: bridge

volumes:
  redis_data:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  ollama_data:

configs:
  redis_config:
    file: ./config/redis.conf
  neo4j_config:
    file: ./config/neo4j.conf