name: Validate Docs & Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  get-changed-files:
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.changed-files.outputs.added_modified }}
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: Ana06/get-changed-files@v2.3.0
        with:
          filter: "docs/**"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: |
          uv sync 

      - name: Lint Docs
        run: make lint-docs

      - name: Format Code
        run: make format

      - name: Lint Code
        run: make lint

#  validate-docker-compose:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check out repository
#        uses: actions/checkout@v4
#
#      - name: Set up Docker
#        uses: docker/setup-buildx-action@v3
#
#      - name: Build Docker Compose
#        run: |
#          docker-compose -f docker-compose.yml build
#
#      - name: Validate Docker Compose
#        run: |
#          docker-compose -f docker-compose.yml config --quiet
#
#      - name: Run Docker Compose Services
#        run: |
#          docker-compose up -d
#
#      - name: Wait for services to be healthy
#        run: |
#          sleep 10  # Adjust based on startup time
#          docker ps --filter "health=healthy"
#
#      - name: Stop and clean up
#        run: |
#          docker-compose down